english_examples = [
    {
        "input": "Plan and organize a wedding event within the next two months with the following specifications: evening time slot, outdoor venue, 20 guests, budget of $500, classic white theme, and live music. The provided budget is not sufficient for a wedding event with these specifications. I suggest a new budget of $2,500 to create a more realistic plan.",
        "answer": "{{\"before_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (USD)\"], "
                  "[\"Budget review and adjustments\", \"3 hours\", \"2 months before\", \"0\"], "
                  "[\"Guest list preparation\", \"8 hours\", \"7 weeks before\", \"0\"], "
                  "[\"Venue scouting and selection\", \"10 hours\", \"6 weeks before\", \"200\"], "
                  "[\"Hire Wedding Planner and Vendors (Optional)\", \"15 hours\", \"6 weeks before\", \"250\"], "
                  "[\"Permits and licenses\", \"5 hours\", \"6 weeks before\", \"50\"], "
                  "[\"Finalize venue booking\", \"5 hours\", \"5 weeks before\", \"400\"], "
                  "[\"Weather contingency planning\", \"4 hours\", \"5 weeks before\", \"0\"], "
                  "[\"Live music booking\", \"10 hours\", \"5 weeks before\", \"200\"], "
                  "[\"Catering arrangement\", \"20 hours\", \"4 weeks before\", \"600\"], "
                  "[\"Decor and theme design\", \"15 hours\", \"4 weeks before\", \"200\"], "
                  "[\"Equipment rental (chairs, tables, etc.)\", \"8 hours\", \"3 weeks before\", \"150\"], "
                  "[\"Wedding attire and accessories\", \"10 hours\", \"3 weeks before\", \"150\"], "
                  "[\"Photography and videography\", \"12 hours\", \"3 weeks before\", \"250\"], "
                  "[\"Transport for Guests (Optional)\", \"5 hours\", \"3 weeks before\", \"50\"], "
                  "[\"Event timeline and schedule\", \"6 hours\", \"3 weeks before\", \"0\"], "
                  "[\"Vendor finalizations\", \"10 hours\", \"2 weeks before\", \"0\"], "
                  "[\"Vendor confirmation\", \"3 hours\", \"2 weeks before\", \"0\"], "
                  "[\"Total\", \"169 hours\", \"2 months\", \"2,250\"] ], "

                  "\"on_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (USD)\"], "
                  "[\"Venue setup\", \"5 hours\", \"On event day\", \"0\"], "
                  "[\"Vendor coordination\", \"3 hours\", \"On event day\", \"0\"], "
                  "[\"Live music coordination\", \"5 hours\", \"On event day\", \"0\"], "
                  "[\"Photography and videography\", \"5 hours\", \"On event day\", \"0\"], "
                  "[\"Guest reception and assistance\", \"2 hours\", \"On event day\", \"0\"], "
                  "[\"Wedding ceremony\", \"1 hour\", \"On event day\", \"0\"], "
                  "[\"Catering service\", \"2 hours\", \"On event day\", \"0\"], "
                  "[\"Event management\", \"5 hours\", \"On event day\", \"0\"], "
                  "[\"Emergency handling\", \"5 hours\", \"On event day\", \"0\"], "
                  "[\"Venue cleanup\", \"3 hours\", \"On event day\", \"0\"], "
                  "[\"Vendor payments\", \"1 hour\", \"On event day\", \"0\"], "
                  "[\"Feedback collection\", \"1 hour\", \"On event day\", \"0\"], "
                  "[\"Total\", \"43 hours\", \"1 day\", \"0\"] ], "

                  "\"after_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (USD)\"], "
                  "[\"Equipment return\", \"2 hours\", \"1 day after\", \"0\"], "
                  "[\"Event review\", \"1 hour\", \"2 days after\", \"0\"], "
                  "[\"Financial closure\", \"2 hours\", \"2 days after\", \"0\"], "
                  "[\"Total\", \"5 hours\", \"2 days\", \"0\"] ]}}"
    },
    {
        "input": "Organize a technology conference within the next four months. The event, lasting a full day from morning to evening at a convention center, should accommodate 300 guests within a budget of $1,000. Focus on a futuristic/technological theme with activities such as keynote speeches, panel discussions, tech demos, and networking sessions. Please note that the provided budget is not feasible for such an event, so I proposed a new budget - $30,000",
        "answer": "{{\"before_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (USD)\"], "
                  "[\"Budget review and allocation\", \"5 hours\", \"4 months before\", \"0\"], "
                  "[\"Setting up Registration and IT Systems\", \"45 hours\", \"3.5 months before\", \"1,500\"], "
                  "[\"Marketing and Promotion Campaign\", \"70 hours\", \"3.5 months before\", \"2,000\"], "
                  "[\"Venue Booking and Preparations\", \"50 hours\", \"3 months before\", \"4,000\"], "
                  "[\"Establishing Safety and Emergency Plans\", \"20 hours\", \"3 months before\", \"1,000\"], "
                  "[\"Inviting Speakers and Panelists\", \"60 hours\", \"3 months before\", \"3,000\"], "
                  "[\"Theme Design and Decor\", \"40 hours\", \"2.5 months before\", \"2,500\"], "
                  "[\"Organizing Tech Demos\", \"80 hours\", \"2.5 months before\", \"2,500\"], "
                  "[\"Audio/Visual Equipment and Tech Support\", \"40 hours\", \"2 months before\", \"2,000\"], "
                  "[\"Catering Services\", \"50 hours\", \"2 months before\", \"3,500\"], "
                  "[\"Coordinating Staff and Volunteers\", \"30 hours\", \"2 months before\", \"1,000\"], "
                  "[\"Preparing Participant Materials and Packages\", \"35 hours\", \"6 weeks before\", \"1,500\"], "
                  "[\"Total\", \"525 hours\", \"Four months\", \"24,500\"] ], "

                  "\"on_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (USD)\"], "
                  "[\"Final Setup and Testing of Venue Equipment\", \"4 hours\", \"Morning of event\", \"500\"], "
                  "[\"Welcoming Attendees and Registration\", \"2 hours\", \"Start of event\", \"500\"], "
                  "[\"Opening Ceremony and Keynote Address\", \"1 hour\", \"Morning session\", \"500\"], "
                  "[\"Panel Discussions and Expert Forums\", \"3 hours\", \"Morning session\", \"500\"], "
                  "[\"Lunch Break and Networking\", \"1 hour\", \"Midday\", \"1,000\"], "
                  "[\"Afternoon Sessions: Tech Demos and Workshops\", \"3 hours\", \"Afternoon\", \"500\"], "
                  "[\"Evening Closing Session\", \"1 hour\", \"End of day\", \"$500\"], "
                  "[\"Feedback Collection and Networking Wrap-up\", \"1 hour\", \"Post-event\", \"500\"], "
                  "[\"Debrief with Staff and Post-Event Analysis\", \"2 hours\", \"Post-event\", \"500\"], "
                  "[\"Dismantling and Venue Clearance\", \"2 hours\", \"Post-event\", \"500\"], "
                  "[\"Total\", \"20 hours\", \"1 day\", \"5,500\"] ], "

                  "\"after_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (USD)\"], "
                  "[\"Equipment return\", \"2 hours\", \"1 day after\", \"0\"], "
                  "[\"Event review\", \"1 hour\", \"2 days after\", \"0\"], "
                  "[\"Financial closure\", \"2 hours\", \"2 days after\", \"0\"], "
                  "[\"Total\", \"5 hours\", \"2 days\", \"0\"] ]}}"
    }
]
