vietnamese_examples = [
    {
        "input": "Lên kế hoạch và tổ chức một sự kiện đám cưới gia đình vào tháng sau với các đặc điểm sau: "
                 "thời gian vào buổi trưa, tại khách sạn, dự kiến có 100 khách mời, ngân sách 110 triệu, "
                 "chủ đề lãng mạn và cổ điển, với sự biểu diễn của một ban nhạc trực tiếp",
        "answer": "{{\"before_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (VND)\"], "
                  "[\"Chuẩn bị danh sách khách mời\", \"8 giờ\", \"4 tuần trước\", \"0\"], "
                  "[\"Xem xét và điều chỉnh ngân sách\", \"3 giờ\", \"4 tuần trước\", \"0\"], "
                  "[\"Thuê người quản lý và nhà cung cấp dịch vụ\", \"15 giờ\", \"3.5 tuần trước\", \"15,000,000\"], "
                  "[\"Khảo sát và chọn địa điểm\", \"10 giờ\", \"3.5 tuần trước\", \"10,000,000\"], "
                  "[\"Hoàn tất việc đặt địa điểm\", \"5 giờ\", \"3 tuần trước\", \"20,000,000\"], "
                  "[\"Đặt ban nhạc trực tiếp\", \"10 giờ\", \"3 tuần trước\", \"15,000,000\"], "
                  "[\"Chuẩn bị dịch vụ ẩm thực\", \"20 giờ\", \"3 tuần trước\", \"10,000,000\"], "
                  "[\"Thiết kế trang trí và chủ đề\", \"15 giờ\", \"2.5 tuần trước\", \"10,000,000\"], "
                  "[\"Thuê đồ (ghế, bàn, v.v.)\", \"8 giờ\", \"2 tuần trước\", \"5,000,000\"], "
                  "[\"Chọn trang phục và phụ kiện\", \"10 giờ\", \"2 tuần trước\", \"5,000,000\"], "
                  "[\"Chụp ảnh và quay video\", \"12 giờ\", \"2 tuần trước\", \"10,000,000\"], "
                  "[\"Chỗ ở cho khách mời\", \"5 giờ\", \"1.5 tuần trước\", \"5,000,000\"], "
                  "[\"Vận chuyển cho khách mời\", \"5 giờ\", \"1.5 tuần trước\", \"5,000,000\"], "
                  "[\"Dự phòng về thời tiết\", \"4 giờ\", \"1 tuần trước\", \"0\"], "
                  "[\"Lên lịch và thời gian sự kiện\", \"6 giờ\", \"1 tuần trước\", \"0\"], "
                  "[\"Đảm bảo cuối cùng với nhà cung cấp\", \"10 giờ\", \"5 ngày trước\", \"0\"], "
                  "[\"Xác nhận với nhà cung cấp\", \"3 giờ\", \"2 ngày trước\", \"0\"], "
                  "[\"Tổng cộng\", \"159 giờ\", \"1 tháng\", \"110,000,000\"] ], "

                  "\"on_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget\"], "
                  "[\"Thiết lập địa điểm\", \"3 giờ\", \"Buổi sáng ngày sự kiện\", \"0\"], "
                  "[\"Phối hợp với nhà cung cấp dịch vụ\", \"3 giờ\", \"Trong ngày sự kiện\", \"0\"], "
                  "[\"Phối hợp với ban nhạc trực tiếp\", \"5 giờ\", \"Trong ngày sự kiện\", \"0\"], "
                  "[\"Chụp ảnh và quay video\", \"5 giờ\", \"Trong ngày sự kiện\", \"0\"], "
                  "[\"Tiếp đón và hướng dẫn khách mời\", \"2 giờ\", \"Khai mạc sự kiện\", \"0\"], "
                  "[\"Lễ kết hôn\", \"1 giờ\", \"Thời gian chỉ định\", \"0\"], "
                  "[\"Dịch vụ ẩm thực\", \"2 giờ\", \"Thời gian chỉ định\", \"0\"], "
                  "[\"Quản lý sự kiện\", \"5 giờ\", \"Trong ngày sự kiện\", \"0\"], "
                  "[\"Xử lý tình huống khẩn cấp\", \"5 giờ\", \"Trong ngày sự kiện\", \"0\"], "
                  "[\"Dọn dẹp địa điểm\", \"3 giờ\", \"Kết thúc sự kiện\", \"0\"], "
                  "[\"Thanh toán cho nhà cung cấp\", \"1 giờ\", \"Sau sự kiện\", \"0\"], "
                  "[\"Thu thập ý kiến\", \"1 giờ\", \"Sau sự kiện\", \"0\"], "
                  "[\"Tổng cộng\", \"40 giờ\", \"1 ngày\", \"0\"] ], "

                  "\"after_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget\"], "
                  "[\"Trả lại thiết bị\", \"2 giờ\", \"1 ngày sau\", \"0\"], "
                  "[\"Xem xét sự kiện\", \"1 giờ\", \"2 ngày sau\", \"0\"], "
                  "[\"Đóng gói tài chính\", \"2 giờ\", \"2 ngày sau\", \"0\"], "
                  "[\"Tổng cộng\", \"5 giờ\", \"2 ngày\", \"0\"] ]}}"
    },
    {
        "input": "Lên kế hoạch và tổ chức một tiệc sinh nhật với chủ đề kỳ diệu, màu hồng và trắng trong vòng một tháng tại nhà riêng "
                 "cho 30 khách mời, kéo dài 4 tiếng vào buổi tối. Ngân sách dự kiến là 3 triệu VND. Tuy nhiên, ngân sách này không đủ "
                 "để thực hiện tất cả các yêu cầu, đặc biệt là chi phí cho ảo thuật gia, trò chơi và karaoke. Do đó, tôi đề xuất một "
                 "ngân sách mới là 10 triệu VND.",
        "answer": "{{\"before_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget (VND)\"], "
                  "[\"Lập kế hoạch chi tiết và ngân sách\", \"5 giờ\", \"4 tuần trước\", \"0\"], "
                  "[\"Đặt ảo thuật gia\", \"8 giờ\", \"3 tuần trước\", \"3,000,000\"], "
                  "[\"Mua sắm trang trí\", \"10 giờ\", \"3 tuần trước\", \"2,000,000\"], "
                  "[\"Chuẩn bị trò chơi\", \"10 giờ\", \"2.5 tuần trước\", \"1,000,000\"], "
                  "[\"Thuê hệ thống karaoke\", \"5 giờ\", \"2 tuần trước\", \"2,000,000\"], "
                  "[\"Chuẩn bị thực phẩm và bánh sinh nhật\", \"12 giờ\", \"1.5 tuần trước\", \"2,000,000\"], "
                  "[\"Tổng cộng\", \"45 giờ\", \"1 tháng\", \"10,000,000\"] ], "

                  "\"on_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget\"], "
                  "[\"Trang trí không gian tổ chức\", \"3 giờ\", \"Buổi sáng ngày sự kiện\", \"0\"], "
                  "[\"Kiểm tra hệ thống karaoke\", \"1 giờ\", \"Trước sự kiện\", \"0\"], "
                  "[\"Đón tiếp khách mời\", \"1 giờ\", \"Khai mạc sự kiện\", \"0\"], "
                  "[\"Biểu diễn ảo thuật\", \"1 giờ\", \"Trong sự kiện\", \"0\"], "
                  "[\"Thưởng thức thực phẩm và bánh\", \"1 giờ\", \"Trong sự kiện\", \"0\"], "
                  "[\"Trò chơi vận động\", \"1 giờ\", \"Trong sự kiện\", \"0\"], "
                  "[\"Karaoke và giải trí\", \"1 giờ\", \"Trong sự kiện\", \"0\"], "
                  "[\"Tổng cộng\", \"8 giờ\", \"4 tiếng\", \"0\"] ], "

                  "\"after_event_day\": "
                  "[ [\"Task Name\", \"Estimated Effort\", \"Suggested Deadline\", \"Allocated Budget\"], "
                  "[\"Thu dọn trang trí và vệ sinh\", \"4 giờ\", \"1 ngày sau\", \"0\"], "
                  "[\"Tổng kết sự kiện và đánh giá\", \"2 giờ\", \"2 ngày sau\", \"0\"], "
                  "[\"Đóng gói tài chính\", \"2 giờ\", \"2 ngày sau\", \"0\"], "
                  "[\"Tổng cộng\", \"8 giờ\", \"1 ngày\", \"0\"] ]}}"
    }
]
