# All the variables should be queried from .env file
log_level: "DEBUG"
openai:
  api_key: !ENV ${OPENAI_API_KEY}
  model_name: "gpt-3.5-turbo"
app:
  host: "0.0.0.0"
  port: "8000"
database:
  host: !ENV ${MYSQL_HOST}
  user: !ENV ${MYSQL_USER}
  password: !ENV ${MYSQL_PASSWORD}
  database: !ENV ${MYSQL_DATABASE}