english_examples = [
    {
        "input": "{{\"Purpose of the event\": \"Wedding\", \"Deadline\": \"Two months\", \"Duration\": \"5 hours\", "
                 "\"Location\": \"Outdoor venue\", \"Number of guests\": 20, "
                 "\"Budget range\": \"$500\", \"Specific themes or colors\": \"Classic white\", "
                 "\"Entertainment/activities\": \"Live music\"}}",
        "answer": "{{\"Category\": \"Private\", "

                  "\"Command\": "
                  "\"Plan and organize a wedding event within the next two months with the following specifications: "
                  "evening time slot, outdoor venue, 20 guests, budget of $500, classic white theme, and live music. "
                  "The provided budget is not sufficient for a wedding event with these specifications. I suggest a new "
                  "budget of $2,500 to create a more realistic plan. Below is the proposed plan:\", "

                  "\"Before the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost ($)\"], "
                  "[\"Venue scouting and selection\", \"10\", \"2 weeks\", \"200\"], "
                  "[\"Finalize venue booking\", \"5\", \"3 days\", \"400\"], "
                  "[\"Hire Wedding Planner and Vendors (DIY options considered)(Optional)\", \"15\", \"1 week\", \"250\"], "
                  "[\"Guest list preparation\", \"8\", \"1 week\", \"0\"], "
                  "[\"Live music booking\", \"10\", \"1 week\", \"200\"], "
                  "[\"Catering arrangement\", \"20\", \"2 weeks\", \"600\"], "
                  "[\"Decor and theme design\", \"15\", \"2 weeks\", \"200\"], "
                  "[\"Equipment rental (chairs, tables, etc.)\", \"8\", \"1 week\", \"150\"], "
                  "[\"Transport for Guests (Limited or local)(Optional)\", \"5\", \"1 week\", \"50\"], "
                  "[\"Vendor finalizations\", \"10\", \"1 week\", \"0\"], "
                  "[\"Event timeline and schedule\", \"6\", \"3 days\", \"0\"], "
                  "[\"Wedding attire and accessories\", \"10\", \"2 weeks\", \"150\"], "
                  "[\"Photography and videography\", \"12\", \"2 weeks\", \"250\"], "
                  "[\"Permits and licenses\", \"5\", \"1 week\", \"50\"], "
                  "[\"Weather contingency planning\", \"4\", \"2 days\", \"0\"], "
                  "[\"Budget review and adjustments\", \"3\", \"2 days\", \"0\"], "
                  "[\"Vendor confirmation\", \"3\", \"2 days\", \"0\"], "
                  "[\"Total\", \"169\", \"2 months\", \"2,250\"] ], "

                  "\"On the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost ($)\"], "
                  "[\"Venue setup\", \"5\", \"5 hours\", \"0\"], "
                  "[\"Vendor coordination\", \"3\", \"3 hours\", \"0\"], "
                  "[\"Guest reception and assistance\", \"2\", \"2 hours\", \"0\"], "
                  "[\"Wedding ceremony\", \"1\", \"1 hour\", \"0\"], "
                  "[\"Catering service\", \"2\", \"2 hours\", \"0\"], "
                  "[\"Event management\", \"5\", \"5 hours\", \"0\"], "
                  "[\"Live music coordination\", \"5\", \"5 hours\", \"0\"], "
                  "[\"Photography and videography\", \"5\", \"5 hours\", \"0\"], "
                  "[\"Emergency handling\", \"5\", \"5 hours\", \"0\"], "
                  "[\"Venue cleanup\", \"3\", \"3 hours\", \"0\"], "
                  "[\"Vendor payments\", \"1\", \"1 hour\", \"0\"], "
                  "[\"Feedback collection\", \"1\", \"1 hour\", \"0\"], "
                  "[\"Total\", \"43\", \"1 day\", \"0\"] ], "

                  "\"After the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost ($)\"], "
                  "[\"Equipment return\", \"2\", \"Next day\", \"0\"], "
                  "[\"Event review\", \"1\", \"1 day\", \"0\"], "
                  "[\"Financial closure\", \"2\", \"1 day\", \"0\"] ]}}"
    },
    {
        "input": "{{\"Purpose of the event\": \"Technology Conference\", \"Deadline\": \"Four months\", "
                 "\"Duration\": \"Full day\", \"Location\": \"Convention Center\", \"Number of guests\": 300, "
                 "\"Budget range\": \"$1,000\", \"Specific themes or colors\": \"Futuristic/Technological\", "
                 "\"Entertainment/activities\": \"Keynote speeches, panel discussions, tech demos, networking sessions\"}}",
        "answer": "{{\"Category\": \"Corporate\", "

                  "\"Command\": "
                  "\"Organize a technology conference within the next four months. The event, lasting a full day from "
                  "morning to evening at a convention center, should accommodate 300 guests within a budget of $1,000. "
                  "Focus on a futuristic/technological theme with activities such as keynote speeches, panel discussions, "
                  "tech demos, and networking sessions. Please note that the provided budget is not feasible for such an event, "
                  "so I proposed a new budget - $30,000, with the plan below:\", "

                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost ($)\"], "
                  "[\"Venue Booking and Preparations\", \"50\", \"1 month\", \"4,000\"], "
                  "[\"Theme Design and Decor\", \"40\", \"3 weeks\", \"2,500\"], "
                  "[\"Inviting Speakers and Panelists\", \"60\", \"6 weeks\", \"3,000\"], "
                  "[\"Organizing Tech Demos\", \"80\", \"2 months\", \"2,500\"], "
                  "[\"Catering Services\", \"50\", \"1 month\", \"3,500\"], "
                  "[\"Setting up Registration and IT Systems\", \"45\", \"1.5 months\", \"1,500\"], "
                  "[\"Audio/Visual Equipment and Tech Support\", \"40\", \"1 month\", \"2,000\"], "
                  "[\"Marketing and Promotion Campaign\", \"70\", \"2.5 months\", \"2,000\"], "
                  "[\"Coordinating Staff and Volunteers\", \"30\", \"1 month\", \"1,000\"], "
                  "[\"Preparing Participant Materials and Packages\", \"35\", \"3 weeks\", \"1,500\"], "
                  "[\"Establishing Safety and Emergency Plans\", \"20\", \"3 weeks\", \"1,000\"], "
                  "[\"Total\", \"520\", \"Four months\", \"24,500\"] ], "

                  "\"On the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost ($)\"], "
                  "[\"Final Setup and Testing of Venue Equipment\", \"4\", \"04:00\", \"500\"], "
                  "[\"Welcoming Attendees and Registration\", \"2\", \"2 hours\", \"500\"], "
                  "[\"Opening Ceremony and Keynote Address\", \"1\", \"1 hour\", \"500\"], "
                  "[\"Panel Discussions and Expert Forums\", \"3\", \"3 hours\", \"500\"], "
                  "[\"Lunch Break and Networking\", \"1\", \"1.5 hours\", \"1,000\"], "
                  "[\"Afternoon Sessions: Tech Demos and Workshops\", \"3\", \"3 hours\", \"500\"], "
                  "[\"Evening Closing Session\", \"1\", \"1 hour\", \"500\"], "
                  "[\"Feedback Collection and Networking Wrap-up\", \"1\", \"1 hour\", \"500\"], "
                  "[\"Dismantling and Venue Clearance\", \"2\", \"2 hours\", \"500\"], "
                  "[\"Debrief with Staff and Post-Event Analysis\", \"2\", \"2 hours\", \"500\"], "
                  "[\"Total\", \"20\", \"1 day\", \"5,500\"] ], "

                  "\"After the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost ($)\"], "
                  "[\"Equipment return\", \"2\", \"Next day\", \"0\"], "
                  "[\"Event review\", \"1\", \"1 day\", \"0\"], "
                  "[\"Financial closure\", \"2\", \"1 day\", \"0\"] ]}}"
    }
]
