vietnamese_examples = [
    {
        "input": "{{\"Mục đích của sự kiện là gì?\": \"Đám cưới gia đình\", \"Bạn muốn tổ chức vào thời gian nào?\": \"Tháng sau\", "
                 "\"Buổi tiệc kéo dài bao lâu?\": \"3 tiếng\", \"Địa điểm bạn mong muốn tổ chức?\": \"Khách sạn\", "
                 "\"Số lượng khách mời dự kiến?\": \"100 người\", \"Ngân sách dự trù cho sự kiện này?\": \"110 triệu\", "
                 "\"Bạn có ý tưởng nào về chủ đề hoặc màu sắc không?\": \"Lãng mạn và cổ điển\", "
                 "\"Loại hình giải trí hoặc hoạt động bạn muốn tổ chức?\": \"Ban nhạc trực tiếp\"}}",
        "answer": "{{\"Category\": \"Private\", "

                  "\"Command\": "
                  "\"Lên kế hoạch và tổ chức một sự kiện đám cưới gia đình vào tháng sau với các đặc điểm sau: "
                  "thời gian vào buổi trưa, tại khách sạn, dự kiến có 100 khách mời, ngân sách 110 triệu, "
                  "chủ đề lãng mạn và cổ điển, với sự biểu diễn của một ban nhạc trực tiếp. Dưới đây là bản thảo kế hoạch:\", "

                  "\"Before the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost (VND)\"], "
                  "[\"Khảo sát và chọn địa điểm\", \"10\", \"2 tuần\", \"10,000,000\"], "
                  "[\"Hoàn tất việc đặt địa điểm\", \"5\", \"3 ngày\", \"20,000,000\"], "
                  "[\"Thuê người quản lý và nhà cung cấp dịch vụ\", \"15\", \"1 tuần\", \"15,000,000\"], "
                  "[\"Chuẩn bị danh sách khách mời\", \"8\", \"1 tuần\", \"0\"], "
                  "[\"Đặt ban nhạc trực tiếp\", \"10\", \"1 tuần\", \"15,000,000\"], "
                  "[\"Chuẩn bị dịch vụ ẩm thực\", \"20\", \"2 tuần\", \"10,000,000\"], "
                  "[\"Thiết kế trang trí và chủ đề\", \"15\", \"2 tuần\", \"10,000,000\"], "
                  "[\"Thuê đồ (ghế, bàn, v.v.)\", \"8\", \"1 tuần\", \"5,000,000\"], "
                  "[\"Vận chuyển cho khách mời\", \"5\", \"1 tuần\", \"5,000,000\"], "
                  "[\"Đảm bảo cuối cùng với nhà cung cấp\", \"10\", \"1 tuần\", \"0\"], "
                  "[\"Lên lịch và thời gian sự kiện\", \"6\", \"3 ngày\", \"0\"], "
                  "[\"Chọn trang phục và phụ kiện\", \"10\", \"2 tuần\", \"5,000,000\"], "
                  "[\"Chỗ ở cho khách mời\", \"5\", \"1 tuần\", \"5,000,000\"], "
                  "[\"Chụp ảnh và quay video\", \"12\", \"2 tuần\", \"10,000,000\"], "
                  "[\"Dự phòng về thời tiết\", \"4\", \"2 ngày\", \"0\"], "
                  "[\"Xem xét và điều chỉnh ngân sách\", \"3\", \"2 ngày\", \"0\"], "
                  "[\"Xác nhận với nhà cung cấp\", \"3\", \"2 ngày\", \"0\"], "
                  "[\"Tổng cộng\", \"159\", \"1 tháng\", \"110,000,000\"] ], "

                  "\"On the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost (VND)\"], "
                  "[\"Thiết lập địa điểm\", \"3\", \"3 tiếng\", \"0\"], "
                  "[\"Phối hợp với nhà cung cấp dịch vụ\", \"3\", \"3 tiếng\", \"0\"], "
                  "[\"Tiếp đón và hướng dẫn khách mời\", \"2\", \"2 tiếng\", \"0\"], "
                  "[\"Lễ kết hôn\", \"1\", \"1 tiếng\", \"0\"], "
                  "[\"Dịch vụ ẩm thực\", \"2\", \"2 tiếng\", \"0\"], "
                  "[\"Quản lý sự kiện\", \"5\", \"5 tiếng\", \"0\"], "
                  "[\"Phối hợp với ban nhạc trực tiếp\", \"5\", \"5 tiếng\", \"0\"], "
                  "[\"Chụp ảnh và quay video\", \"5\", \"5 tiếng\", \"0\"], "
                  "[\"Xử lý tình huống khẩn cấp\", \"5\", \"5 tiếng\", \"0\"], "
                  "[\"Dọn dẹp địa điểm\", \"3\", \"3 tiếng\", \"0\"], "
                  "[\"Thanh toán cho nhà cung cấp\", \"1\", \"1 tiếng\", \"0\"], "
                  "[\"Thu thập ý kiến\", \"1\", \"1 tiếng\", \"0\"], "
                  "[\"Tổng cộng\", \"40\", \"1 ngày\", \"0\"] ], "

                  "\"After the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost (VND)\"], "
                  "[\"Trả lại thiết bị\", \"2\", \"Ngày tiếp theo\", \"0\"], "
                  "[\"Xem xét sự kiện\", \"1\", \"1 ngày\", \"0\"], "
                  "[\"Đóng gói tài chính\", \"2\", \"1 ngày\", \"0\"], "
                  "[\"Tổng cộng\", \"5\", \"2 ngày\", \"0\"] ]}}"
    },
    {
        "input": "{{\"Mục đích của sự kiện là gì?\": \"Tiệc sinh nhật\", \"Bạn muốn tổ chức vào thời gian nào?\": \"Một tháng\", "
                 "\"Buổi tiệc kéo dài bao lâu?\": \"4 tiếng\", \"Địa điểm bạn mong muốn tổ chức?\": \"Nhà riêng\", "
                 "\"Số lượng khách mời dự kiến?\": \"30 người\", \"Ngân sách dự trù cho sự kiện này?\": \"3 triệu VND\", "
                 "\"Bạn có ý tưởng nào về chủ đề hoặc màu sắc không?\": \"Màu hồng và trắng, chủ đề kỳ diệu\", "
                 "\"Loại hình giải trí hoặc hoạt động bạn muốn tổ chức?\": \"Ảo thuật, trò chơi vận động và karaoke\"}}",
        "answer": "{{\"Category\": \"Private\", "

                  "\"Command\": "
                  "\"Lên kế hoạch và tổ chức một tiệc sinh nhật với chủ đề kỳ diệu, màu hồng và trắng trong vòng một tháng tại nhà riêng "
                  "cho 30 khách mời, kéo dài 4 tiếng vào buổi tối. Ngân sách dự kiến là 3 triệu VND. Tuy nhiên, ngân sách này không đủ "
                  "để thực hiện tất cả các yêu cầu, đặc biệt là chi phí cho ảo thuật gia, trò chơi và karaoke. Do đó, tôi đề xuất một "
                  "ngân sách mới là 10 triệu VND. Dưới đây là bản kế hoạch:\", "

                  "\"Before the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost (VND)\"], "
                  "[\"Mua sắm trang trí\", \"10\", \"1 tuần\", \"2,000,000\"], "
                  "[\"Đặt ảo thuật gia\", \"8\", \"1 tuần\", \"3,000,000\"], "
                  "[\"Chuẩn bị trò chơi\", \"10\", \"2 tuần\", \"1,000,000\"], "
                  "[\"Thuê hệ thống karaoke\", \"5\", \"1 tuần\", \"2,000,000\"], "
                  "[\"Chuẩn bị thực phẩm và bánh sinh nhật\", \"12\", \"1 tuần\", \"2,000,000\"], "
                  "[\"Tổng cộng\", \"45\", \"Một tháng\", \"10,000,000\"] ], "

                  "\"On the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost (VND)\"], "
                  "[\"Trang trí không gian tổ chức\", \"3\", \"3 giờ\", \"0\"], "
                  "[\"Đón tiếp khách mời\", \"1\", \"1 giờ\", \"0\"], "
                  "[\"Biểu diễn ảo thuật\", \"1\", \"1 giờ\", \"0\"], "
                  "[\"Trò chơi vận động\", \"1\", \"1 giờ\", \"0\"], "
                  "[\"Karaoke và giải trí\", \"1\", \"1 giờ\", \"0\"], "
                  "[\"Thưởng thức thực phẩm và bánh\", \"1\", \"1 giờ\", \"0\"], "
                  "[\"Tổng cộng\", \"8\", \"4 tiếng\", \"0\"] ], "

                  "\"After the event day\": "
                  "[ [\"Stages\", \"Effort (hours)\", \"Duration\", \"Cost (VND)\"], "
                  "[\"Thu dọn trang trí và vệ sinh\", \"4\", \"1 ngày\", \"0\"], "
                  "[\"Tổng kết sự kiện và đánh giá\", \"2\", \"1 ngày\", \"0\"], "
                  "[\"Đóng gói tài chính\", \"2\", \"1 ngày\", \"0\"], "
                  "[\"Tổng cộng\", \"8\", \"1 ngày\", \"0\"] ]}}"
    }
]
