english_examples = [
    {
        "input": "[\"Venue scouting and selection\", \"Finalize venue booking\", \"Hire Wedding Planner and Vendors\", "
                 "\"Guest list preparation\", \"Live music booking\", \"Catering arrangement\", \"Decor and theme design\", "
                 "\"Equipment rental (chairs, tables, etc.)\", \"Transport for Guests (Limited or local)\", "
                 "\"Vendor finalizations\", \"Event timeline and schedule\", \"Wedding attire and accessories\", "
                 "\"Photography and videography\", \"Permits and licenses\", \"Weather contingency planning\", "
                 "\"Budget review and adjustments\", \"Vendor confirmation\"]",
        "answer": "{{"
                  "\"0\": \"Venue\", "
                  "\"1\": \"Venue\", "
                  "\"2\": \"Staffing\", "
                  "\"3\": \"Logistics\", "
                  "\"4\": \"Entertainment\", "
                  "\"5\": \"Food and Drinks\", "
                  "\"6\": \"Decorations and Ambiance\", "
                  "\"7\": \"Technology\", "
                  "\"8\": \"Transportation\", "
                  "\"9\": \"Staffing\", "
                  "\"10\": \"Logistics\", "
                  "\"11\": \"Others\", "
                  "\"12\": \"Technology\", "
                  "\"13\": \"Logistics\", "
                  "\"14\": \"Logistics\", "
                  "\"15\": \"Logistics\", "
                  "\"16\": \"Staffing\""
                  "}}"
    },
    {
        "input": "[\"Conference hall reservation\", \"Speaker invitations and confirmations\", \"Audio-visual equipment setup\", "
                 "\"Registration website creation\", \"Promotional materials design\", \"Catering for lunch and coffee breaks\", "
                 "\"Name badge printing\", \"Session schedule planning\", \"Social media marketing campaign\", "
                 "\"Hotel block booking for attendees\", \"Transportation between venue and hotels\", "
                 "\"Sponsor acquisition and management\", \"Post-event survey preparation\", "
                 "\"On-site registration desk setup\", \"Emergency response plan\"]",
        "answer": "{{"
                  "\"0\": \"Venue\", "
                  "\"1\": \"Staffing\", "
                  "\"2\": \"Technology\", "
                  "\"3\": \"Technology\", "
                  "\"4\": \"Marketing and Promotion\", "
                  "\"5\": \"Food and Drinks\", "
                  "\"6\": \"Printing and Signage\", "
                  "\"7\": \"Logistics\", "
                  "\"8\": \"Marketing and Promotion\", "
                  "\"9\": \"Accommodation\", "
                  "\"10\": \"Transportation\", "
                  "\"11\": \"Marketing and Promotion\", "
                  "\"12\": \"Technology\", "
                  "\"13\": \"Logistics\", "
                  "\"14\": \"Logistics\""
                  "}}"
    },
    {
        "input": "[\"Park permit acquisition\", \"Stage and sound system rental\", \"Local band bookings\", "
                 "\"Food truck coordination\", \"Portable restroom rentals\", \"Waste management plan\", "
                 "\"Security team hiring\", \"First aid station setup\", \"Event map creation and printing\", "
                 "\"Volunteer recruitment and training\", \"Social media event page creation\", "
                 "\"Sponsorship packages development\", \"Children's activity area planning\", "
                 "\"Parking arrangement with nearby lots\", \"Contingency plan for bad weather\"]",
        "answer": "{{"
                  "\"0\": \"Logistics\", "
                  "\"1\": \"Technology\", "
                  "\"2\": \"Entertainment\", "
                  "\"3\": \"Food and Drinks\", "
                  "\"4\": \"Logistics\", "
                  "\"5\": \"Logistics\", "
                  "\"6\": \"Staffing\", "
                  "\"7\": \"Logistics\", "
                  "\"8\": \"Printing and Signage\", "
                  "\"9\": \"Staffing\", "
                  "\"10\": \"Marketing and Promotion\", "
                  "\"11\": \"Marketing and Promotion\", "
                  "\"12\": \"Entertainment\", "
                  "\"13\": \"Transportation\", "
                  "\"14\": \"Logistics\""
                  "}}"
    }
]
