vietnamese_examples = [
    {
        "input": "[\"Khảo sát và chọn địa điểm\", \"Hoàn tất việc đặt địa điểm\", \"Thuê người tổ chức sự kiện và nhà cung cấp\", "
                 "\"Lập danh sách khách mời\", \"Đặt nhạc sống\", \"Sắp xếp ăn uống\", \"Thiết kế trang trí và chủ đề\", "
                 "\"Thuê thiết bị (ghế, bàn, v.v.)\", \"Vận chuyển cho khách (giới hạn hoặc địa phương)\", "
                 "\"Hoàn tất các nhà cung cấp\", \"Lập kế hoạch thời gian và lịch trình sự kiện\", \"Quần áo và phụ kiện cưới\", "
                 "\"Nhiếp ảnh và quay video\", \"Giấy phép và giấy tờ\", \"Kế hoạch dự phòng cho thời tiết\", "
                 "\"Rà soát và điều chỉnh ngân sách\", \"Xác nhận với nhà cung cấp\"]",
        "answer": "{{"
                  "\"0\": \"Địa Điểm\", "
                  "\"1\": \"Địa Điểm\", "
                  "\"2\": \"Nhân Sự\", "
                  "\"3\": \"Hậu Cần\", "
                  "\"4\": \"Giải Trí\", "
                  "\"5\": \"Thức Ăn và Đồ Uống\", "
                  "\"6\": \"Trang Trí và Không Khí\", "
                  "\"7\": \"Công Nghệ\", "
                  "\"8\": \"Vận Chuyển\", "
                  "\"9\": \"Nhân Sự\", "
                  "\"10\": \"Hậu Cần\", "
                  "\"11\": \"Khác\", "
                  "\"12\": \"Công Nghệ\", "
                  "\"13\": \"Hậu Cần\", "
                  "\"14\": \"Hậu Cần\", "
                  "\"15\": \"Hậu Cần\", "
                  "\"16\": \"Nhân Sự\""
                  "}}"
    },
    {
        "input": "[\"Đặt phòng hội nghị\", \"Mời và xác nhận diễn giả\", \"Thiết lập thiết bị âm thanh và hình ảnh\", "
                 "\"Tạo trang web đăng ký\", \"Thiết kế tài liệu quảng cáo\", \"Đặt tiệc trưa và giải lao\", "
                 "\"In thẻ tên\", \"Lập lịch trình các phiên họp\", \"Chiến dịch marketing trên mạng xã hội\", "
                 "\"Đặt khối phòng khách sạn cho người tham dự\", \"Sắp xếp đưa đón giữa địa điểm và khách sạn\", "
                 "\"Tìm kiếm và quản lý nhà tài trợ\", \"Chuẩn bị khảo sát sau sự kiện\", "
                 "\"Thiết lập quầy đăng ký tại chỗ\", \"Kế hoạch ứng phó khẩn cấp\"]",
        "answer": "{{"
                  "\"0\": \"Địa Điểm\", "
                  "\"1\": \"Nhân Sự\", "
                  "\"2\": \"Công Nghệ\", "
                  "\"3\": \"Công Nghệ\", "
                  "\"4\": \"Marketing và Quảng Bá\", "
                  "\"5\": \"Thức Ăn và Đồ Uống\", "
                  "\"6\": \"In Ấn và Biển Hiệu\", "
                  "\"7\": \"Hậu Cần\", "
                  "\"8\": \"Marketing và Quảng Bá\", "
                  "\"9\": \"Chỗ Ở\", "
                  "\"10\": \"Vận Chuyển\", "
                  "\"11\": \"Marketing và Quảng Bá\", "
                  "\"12\": \"Công Nghệ\", "
                  "\"13\": \"Hậu Cần\", "
                  "\"14\": \"Hậu Cần\""
                  "}}"
    },
    {
        "input": "[\"Xin giấy phép tổ chức tại công viên\", \"Thuê sân khấu và hệ thống âm thanh\", \"Đặt ban nhạc địa phương\", "
                 "\"Điều phối xe bán đồ ăn\", \"Thuê nhà vệ sinh di động\", \"Lập kế hoạch quản lý rác thải\", "
                 "\"Thuê đội ngũ an ninh\", \"Thiết lập trạm sơ cứu\", \"Tạo và in bản đồ sự kiện\", "
                 "\"Tuyển dụng và đào tạo tình nguyện viên\", \"Tạo trang sự kiện trên mạng xã hội\", "
                 "\"Phát triển gói tài trợ\", \"Lên kế hoạch khu vực hoạt động cho trẻ em\", "
                 "\"Sắp xếp bãi đậu xe với các khu vực lân cận\", \"Kế hoạch dự phòng cho thời tiết xấu\"]",
        "answer": "{{"
                  "\"0\": \"Hậu Cần\", "
                  "\"1\": \"Công Nghệ\", "
                  "\"2\": \"Giải Trí\", "
                  "\"3\": \"Thức Ăn và Đồ Uống\", "
                  "\"4\": \"Hậu Cần\", "
                  "\"5\": \"Hậu Cần\", "
                  "\"6\": \"Nhân Sự\", "
                  "\"7\": \"Hậu Cần\", "
                  "\"8\": \"In Ấn và Biển Hiệu\", "
                  "\"9\": \"Nhân Sự\", "
                  "\"10\": \"Marketing và Quảng Bá\", "
                  "\"11\": \"Marketing và Quảng Bá\", "
                  "\"12\": \"Giải Trí\", "
                  "\"13\": \"Vận Chuyển\", "
                  "\"14\": \"Hậu Cần\""
                  "}}"
    }
]
